In [1]:
import pandas as pd

In [2]:
# Cargar los archivos CSV en DataFrames
df_merged = pd.read_csv('merged_file.csv')
df_ecobici = pd.read_csv('ecobici_edited.csv')

In [3]:
# Convertir columnas de estaciones a cadenas y quitar ceros a la izquierda
df_merged['Ciclo_Estacion_Retiro'] = df_merged['Ciclo_Estacion_Retiro'].astype(str).str.lstrip('0')
df_merged['Ciclo_Estacion_Arribo'] = df_merged['Ciclo_Estacion_Arribo'].astype(str).str.lstrip('0')
df_ecobici['num_cicloe'] = df_ecobici['num_cicloe'].astype(str).str.lstrip('0')

In [4]:
# Inspeccionar valores únicos para depurar
print("Valores únicos de Ciclo_Estacion_Retiro:", df_merged['Ciclo_Estacion_Retiro'].unique())
print("Valores únicos de Ciclo_Estacion_Arribo:", df_merged['Ciclo_Estacion_Arribo'].unique())
print("Valores únicos de num_cicloe en ecobici:", df_ecobici['num_cicloe'].unique())

Valores únicos de Ciclo_Estacion_Retiro: ['568' '283' '34' '258' '43' '222' '254' '560' '165' '86' '4' '129' '98'
 '5' '325' '257' '121' '111' '270' '630' '544' '20' '154' '555' '26' '40'
 '8' '390-391' '145' '399' '46' '601' '389' '85' '303' '64' '136' '539'
 '528' '41' '16' '105' '185' '505' '104' '35' '23' '465' '31' '282' '125'
 '29' '33' '126' '549' '30' '7' '384' '553' '593' '164' '188' '113' '12'
 '6' '550' '470' '156' '263' '114' '14' '420' '134' '570' '461' '480'
 '237-238' '286' '52' '10' '299' '581' '162' '232' '460' '133' '494' '67'
 '500' '291' '313' '160' '564' '3' '27' '479' '595' '615' '312' '15' '305'
 '9' '47' '578' '628' '182' '32' '373' '19' '261' '538' '414' '115'
 '107-108' '524' '434' '413' '142' '138' '151' '217' '548' '259' '680'
 '95' '253' '489' '28' '450' '207' '119' '78' '66' '694' '314' '200' '187'
 '468' '566' '242' '488' '385' '120' '194' '260' '642' '345' '147' '54'
 '59' '127' '427' '495' '425' '574' '360' '482' '485' '292' '141' '116'
 '36' '175' '21' '447' '13' '315' '117' '213' '567' '61' '1' '334' '699'
 '210' '11' '92' '38' '82' '536' '24' '181' '563' '556' '118' '68' '170'
 '372' '256' '180' '575' '139' '74' '451' '552' '42' '551' '610' '580'
 '705' '646' '49' '498' '60' '545' '349' '276' '448' '386' '137' '80'
 '523' '146' '396' '87' '228' '645' '525' '81' '37' '709' '110' '392'
 '507' '625' '422' '653' '186' '352' '481' '576' '290' '631' '688' '497'
 '571' '144' '102' '594' '467' '153' '306' '122' '490' '94' '58' '166'
 '209' '50' '204' '569' '517' '329' '484' '634' '398' '622' '191' '167'
 '492' '323' '71' '514' '592' '591' '656' '611' '293' '472' '250' '602'
 '152' '73' '513' '518' '562' '106' '2' '588' '554' '287' '397' '710' '84'
 '192-193' '365' '617' '621' '660' '245' '320' '195' '624' '455' '374'
 '614' '476' '644' '632' '689' '534' '375' '112' '474' '649' '643' '596'
 '648' '641' '205' '77' '174' '401' '123' '330' '130' '70' '711' '148'
 '442' '508' '366' '45' '452' '629' '404' '65' '685' '543' '659' '131'
 '208' '149' '462' '53' '63' '477' '157' '493' '262' '683' '526' '241'
 '475' '584' '124' '219' '76' '394' '357' '654' '337' '224' '459' '279'
 '72' '56' '704' '62' '585' '633' '607' '295' '618' '535' '155' '440'
 '623' '636' '478' '436' '359' '99' '248' '51' '39' '190' '537' '89' '215'
 '327' '301' '233' '542' '496' '234' '79' '466' '377' '449' '423' '561'
 '343' '583' '402' '619' '308' '453' '317' '244' '231' '547' '44' '424'
 '169' '598' '486' '371' '239' '103' '179' '439' '91' '22' '483' '212'
 '512' '529' '48' '509' '521' '412' '280' '605' '100' '285' '326' '223'
 '340' '590' '90' '348' '541' '415' '613' '96' '675' '674' '225' '69'
 '310' '616' '626' '83' '557' '351' '692' '183' '463' '135' '380' '57'
 '597' '163' '445-446' '172' '647' '491' '109' '502' '668' '504' '331'
 '393' '178' '226' '17' '706' '319' '419' '532' '519' '355' '638' '703'
 '297' '132' '296' '573' '499' '173' '577' '456' '520' '652' '211' '540'
 '328' '665' '300' '361' '304' '143' '55' '342' '161' '409' '201' '335'
 '676' '670' '277' '369' '672' '663' '140' '150' '353' '405' '708' '600'
 '168' '243' '322' '128' '650' '171' '370' '430' '216' '438' '288' '428'
 '546' '530' '278' '691' '635' '511' '75' '503' '206' '333' '184' '510'
 '316' '341' '464' '93' '177' '381' '230' '658' '25' '695' '697' '220'
 '255' '669' '336' '158-159' '522' '214' '362' '696' '608' '229' '356'
 '627' '298' '197' '321' '609' '506' '189' '198' '606' '682' '302' '604'
 '309' '294' '637' '640' '657' '437' '281' '441' '693' '246' '579' '432'
 '338' '671' '587' '284' '565' '667' '558' '97' '686' '559' '661' '318'
 '251' '457' '599' '354' '339' '387' '454' '363' '346' '240' '429' '664'
 '655' '684' '681' '702' '690' '18' '358' '221' '433' '347' '531' '458'
 '471' '612' '199' '416' '417' '698' '572' '218' '651' '582' '247' '469'
 '378' '252' '678' '620' '196' '444' '443' '679' '407' '533' '700' '332'
 '603' '515' '662' '639' '202' '324' '673' '235-236' '473' '88' '395'
 '203' '701' '586' '307' '666' '707' '249' '687' '589' '227' '516' '421'
 '367' '677' '501' '527' '271-272' '265' '176' '268-269' '266-267'
 '273-274' '264-275' '487' '1000' '1002']
Valores únicos de Ciclo_Estacion_Arribo: ['572' '596' '64' '23' '126' '483' '688' '539' '120' '85' '518' '1' '2'
 '10' '495' '113' '534' '327' '257' '31' '385' '30' '450' '624' '595' '14'
 '9' '3' '441' '47' '329' '140' '609' '635' '6' '373' '291' '33' '5' '448'
 '118' '547' '685' '26' '81' '505' '34' '44' '21' '568' '315' '102' '35'
 '549' '50' '556' '160' '551' '115' '593' '447' '554' '194' '42' '254'
 '141' '484' '222' '467' '12' '555' '38' '339' '137' '138' '638' '480'
 '261' '32' '191' '620' '174' '40' '580' '125' '581' '123' '121' '171'
 '184' '565' '461' '111' '494' '560' '173' '313' '328' '270' '27' '542'
 '492' '606' '340' '37' '54' '69' '356' '490' '139' '92' '332' '224' '591'
 '260' '538' '476' '104' '67' '548' '519' '628' '51' '280' '187' '144'
 '513' '86' '449' '95' '481' '541' '181' '189' '152' '203' '156' '7' '218'
 '341' '142' '188' '600' '212' '45' '155' '258' '279' '567' '28' '166'
 '147' '103' '80' '509' '259' '575' '133' '52' '374' '290' '405' '475'
 '164' '167' '576' '172' '153' '351' '161' '247' '517' '235-236' '66' '93'
 '499' '170' '658' '336' '110' '22' '321' '163' '200' '604' '97' '708'
 '566' '488' '584' '91' '486' '650' '430' '627' '98' '16' '637' '360' '48'
 '149' '485' '41' '668' '645' '302' '465' '36' '183' '201' '470' '532'
 '471' '130' '514' '293' '578' '510' '124' '392' '312' '87' '401' '11'
 '657' '230' '384' '242' '134' '563' '497' '136' '112' '262' '175' '427'
 '255' '573' '84' '13' '228' '588' '493' '237-238' '614' '107-108' '4'
 '412' '631' '165' '533' '625' '19' '334' '398' '397' '710' '20' '440'
 '119' '424' '43' '559' '445-446' '53' '702' '544' '404' '105' '231' '15'
 '641' '660' '249' '56' '326' '528' '354' '217' '618' '154' '314' '479'
 '190' '478' '46' '63' '243' '195' '507' '68' '229' '99' '283' '223' '168'
 '215' '502' '349' '389' '545' '394' '298' '577' '185' '511' '245' '29'
 '331' '672' '703' '59' '599' '286' '711' '250' '300' '263' '477' '463'
 '148' '659' '292' '78' '694' '288' '644' '603' '585' '543' '239' '278'
 '697' '232' '456' '143' '594' '77' '72' '277' '308' '282' '366' '626'
 '611' '114' '169' '390-391' '459' '482' '117' '338' '654' '221' '619'
 '455' '303' '439' '526' '407' '294' '346' '295' '39' '413' '680' '343'
 '128' '62' '586' '498' '692' '706' '361' '359' '100' '89' '422' '569'
 '205' '253' '73' '129' '88' '244' '546' '196' '310' '192-193' '55' '207'
 '707' '150' '76' '489' '381' '540' '306' '106' '70' '648' '630' '216'
 '535' '561' '616' '58' '146' '61' '553' '369' '646' '632' '621' '617'
 '491' '464' '319' '225' '145' '233' '96' '402' '357' '529' '550' '433'
 '590' '523' '415' '454' '504' '182' '352' '204' '206' '162' '679' '696'
 '208' '468' '506' '438' '299' '131' '372' '474' '704' '355' '65' '57'
 '74' '613' '571' '643' '676' '17' '226' '377' '214' '709' '682' '79'
 '132' '597' '297' '452' '365' '60' '386' '75' '370' '522' '211' '689'
 '367' '8' '323' '135' '520' '122' '530' '220' '49' '24' '508' '219' '276'
 '399' '623' '656' '622' '605' '316' '322' '552' '557' '695' '241' '301'
 '186' '562' '610' '25' '683' '116' '317' '345' '363' '353' '71' '634'
 '305' '442' '521' '607' '304' '570' '640' '285' '342' '378' '651' '420'
 '90' '179' '127' '246' '574' '582' '531' '109' '409' '536' '453' '592'
 '337' '227' '335' '151' '615' '664' '649' '18' '197' '309' '320' '500'
 '466' '705' '296' '158-159' '414' '525' '318' '375' '675' '419' '393'
 '642' '598' '83' '209' '371' '686' '178' '579' '425' '639' '647' '347'
 '693' '180' '444' '460' '472' '690' '82' '362' '429' '252' '396' '587'
 '251' '428' '583' '652' '564' '670' '669' '684' '94' '248' '655' '496'
 '558' '457' '674' '434' '333' '256' '234' '469' '213' '416' '681' '157'
 '700' '601' '423' '698' '677' '602' '284' '437' '661' '612' '671' '458'
 '202' '199' '608' '198' '501' '307' '417' '387' '324' '665' '691' '653'
 '281' '633' '177' '663' '629' '462' '667' '432' '436' '516' '325' '473'
 '395' '515' '503' '443' '678' '348' '673' '210' '330' '512' '636' '589'
 '358' '537' '451' '380' '287' '524' '699' '701' '421' '240' '662' '687'
 '666' '1000' '527' '176' '271-272' '265' '266-267' '264-275' '273-274'
 '268-269' '487' '1002' 'tag 2']
Valores únicos de num_cicloe en ecobici: ['1' '2' '3' '4' '5' '6' '7' '8' '9' '10' '11' '12' '13' '14' '15' '16'
 '17' '18' '19' '20' '21' '22' '23' '24' '25' '26' '27' '28' '29' '30'
 '31' '32' '33' '34' '35' '36' '37' '38' '39' '40' '41' '42' '43' '44'
 '45' '46' '47' '48' '49' '50' '51' '52' '53' '54' '55' '56' '57' '58'
 '59' '60' '61' '62' '63' '64' '65' '66' '67' '68' '69' '70' '71' '72'
 '73' '74' '75' '76' '77' '78' '79' '80' '81' '82' '83' '84' '85' '86'
 '87' '88' '89' '90' '91' '92' '93' '94' '95' '96' '97' '98' '99' '100'
 '102' '103' '104' '105' '106' '107-108' '109' '110' '111' '112' '113'
 '114' '115' '116' '117' '118' '119' '120' '121' '122' '123' '124' '125'
 '126' '127' '128' '129' '130' '131' '132' '133' '134' '135' '136' '137'
 '138' '139' '140' '141' '142' '143' '144' '145' '146' '147' '148' '149'
 '150' '151' '152' '153' '154' '155' '156' '157' '158-159' '160' '161'
 '162' '163' '164' '165' '166' '167' '168' '169' '170' '171' '172' '173'
 '174' '175' '176' '177' '178' '179' '180' '181' '182' '183' '184' '185'
 '186' '187' '188' '189' '190' '191' '192-193' '194' '195' '196' '197'
 '198' '199' '200' '201' '202' '203' '204' '205' '206' '207' '208' '209'
 '210' '211' '212' '213' '214' '215' '216' '217' '218' '219' '220' '221'
 '222' '223' '224' '225' '226' '227' '228' '229' '230' '231' '232' '233'
 '234' '235-236' '237-238' '239' '240' '241' '242' '243' '244' '245' '246'
 '247' '248' '249' '250' '251' '252' '253' '254' '255' '256' '257' '258'
 '259' '260' '261' '262' '263' '264-275' '265' '266-267' '268-269' '270'
 '271-272' '273-274' '276' '277' '278' '279' '280' '281' '282' '283' '284'
 '285' '286' '287' '288' '290' '291' '292' '293' '294' '295' '296' '297'
 '298' '299' '300' '301' '302' '303' '304' '305' '306' '307' '308' '309'
 '310' '312' '313' '314' '315' '316' '317' '318' '319' '320' '321' '322'
 '323' '324' '325' '326' '327' '328' '329' '330' '331' '332' '333' '334'
 '335' '336' '337' '338' '339' '340' '341' '342' '343' '345' '346' '347'
 '348' '349' '351' '352' '353' '354' '355' '356' '357' '358' '359' '360'
 '361' '362' '363' '365' '366' '367' '369' '370' '371' '372' '373' '374'
 '375' '377' '378' '380' '381' '384' '385' '386' '387' '389' '390-391'
 '392' '393' '394' '395' '396' '397' '398' '399' '401' '402' '404' '405'
 '407' '409' '412' '413' '414' '415' '416' '417' '419' '420' '421' '422'
 '423' '424' '425' '427' '428' '429' '430' '432' '433' '434' '436' '437'
 '438' '439' '440' '441' '442' '443' '444' '445-446' '447' '448' '449'
 '450' '451' '452' '453' '454' '455' '456' '457' '458' '459' '460' '461'
 '462' '463' '464' '465' '466' '467' '468' '469' '470' '471' '472' '473'
 '474' '475' '476' '477' '478' '479' '480' '481' '482' '483' '484' '485'
 '486' '487' '488' '489' '490' '491' '492' '493' '494' '495' '496' '497'
 '498' '499' '500' '501' '502' '503' '504' '505' '506' '507' '508' '509'
 '510' '511' '512' '513' '514' '515' '516' '517' '518' '519' '520' '521'
 '522' '523' '524' '525' '526' '527' '528' '529' '530' '531' '532' '533'
 '534' '535' '536' '537' '538' '539' '540' '541' '542' '543' '544' '545'
 '546' '547' '548' '549' '550' '551' '552' '553' '554' '555' '556' '557'
 '558' '559' '560' '561' '562' '563' '564' '565' '566' '567' '568' '569'
 '570' '571' '572' '573' '574' '575' '576' '577' '578' '579' '580' '581'
 '582' '583' '584' '585' '586' '587' '588' '589' '590' '591' '592' '593'
 '594' '595' '596' '597' '598' '599' '600' '601' '602' '603' '604' '605'
 '606' '607' '608' '609' '610' '611' '612' '613' '614' '615' '616' '617'
 '618' '619' '620' '621' '622' '623' '624' '625' '626' '627' '628' '629'
 '630' '631' '632' '633' '634' '635' '636' '637' '638' '639' '640' '641'
 '642' '643' '644' '645' '646' '647' '648' '649' '650' '651' '652' '653'
 '654' '655' '656' '657' '658' '659' '660' '661' '662' '663' '664' '665'
 '666' '667' '668' '669' '670' '671' '672' '673' '674' '675' '676' '677'
 '678' '679' '680' '681' '682' '683' '684' '685' '686' '687' '688' '689'
 '690' '691' '692' '693' '694' '695' '696' '697' '698' '699' '700' '701'
 '702' '703' '704' '705' '706' '707' '708' '709' '710' '711']

In [5]:
# Fusionar la información de la estación de retiro
df_merged = pd.merge(
    df_merged,
    df_ecobici,
    how='left',
    left_on='Ciclo_Estacion_Retiro',
    right_on='num_cicloe',
    suffixes=('', '_Retiro')
)

# Renombrar las columnas de retiro
df_merged = df_merged.rename(columns={
    'nombre_estacion': 'nombre_estacion_Retiro',
    'calle_prin': 'calle_prin_Retiro',
    'calle_secu': 'calle_secu_Retiro',
    'colonia': 'colonia_Retiro',
    'alcaldia': 'alcaldia_Retiro',
    'latitud': 'latitud_Retiro',
    'longitud': 'longitud_Retiro',
    'sitio_de_e': 'sitio_de_e_Retiro'
})

In [6]:
# Fusionar la información de la estación de arribo
df_merged = pd.merge(
    df_merged,
    df_ecobici,
    how='left',
    left_on='Ciclo_Estacion_Arribo',
    right_on='num_cicloe',
    suffixes=('', '_Arribo')
)

# Renombrar las columnas de arribo
df_merged = df_merged.rename(columns={
    'nombre_estacion': 'nombre_estacion_Arribo',
    'calle_prin': 'calle_prin_Arribo',
    'calle_secu': 'calle_secu_Arribo',
    'colonia': 'colonia_Arribo',
    'alcaldia': 'alcaldia_Arribo',
    'latitud': 'latitud_Arribo',
    'longitud': 'longitud_Arribo',
    'sitio_de_e': 'sitio_de_e_Arribo'
})

In [7]:
# Opcional: Inspeccionar valores NaN en el DataFrame resultante
print("Valores NaN en el DataFrame resultante:")
print(df_merged.isna().sum())

Valores NaN en el DataFrame resultante:
Genero_Usuario             84
Edad_Usuario              886
Bici                        0
Ciclo_Estacion_Retiro       0
Fecha_Retiro                0
Hora_Retiro                 0
Ciclo_Estacion_Arribo       0
Fecha_Arribo                0
Hora_Arribo                 0
num_cicloe                  9
nombre_estacion_Retiro      9
calle_prin_Retiro           9
calle_secu_Retiro           9
colonia_Retiro              9
alcaldia_Retiro             9
latitud_Retiro              9
longitud_Retiro             9
sitio_de_e_Retiro           9
num_cicloe_Arribo         479
nombre_estacion_Arribo    479
calle_prin_Arribo         479
calle_secu_Arribo         479
colonia_Arribo            479
alcaldia_Arribo           479
latitud_Arribo            479
longitud_Arribo           479
sitio_de_e_Arribo         479
dtype: int64

In [8]:
# Eliminar filas con valores NaN
df_merged = df_merged.dropna()

In [9]:
print(df_merged.isna().sum())

Genero_Usuario            0
Edad_Usuario              0
Bici                      0
Ciclo_Estacion_Retiro     0
Fecha_Retiro              0
Hora_Retiro               0
Ciclo_Estacion_Arribo     0
Fecha_Arribo              0
Hora_Arribo               0
num_cicloe                0
nombre_estacion_Retiro    0
calle_prin_Retiro         0
calle_secu_Retiro         0
colonia_Retiro            0
alcaldia_Retiro           0
latitud_Retiro            0
longitud_Retiro           0
sitio_de_e_Retiro         0
num_cicloe_Arribo         0
nombre_estacion_Arribo    0
calle_prin_Arribo         0
calle_secu_Arribo         0
colonia_Arribo            0
alcaldia_Arribo           0
latitud_Arribo            0
longitud_Arribo           0
sitio_de_e_Arribo         0
dtype: int64

In [10]:
# Eliminar las columnas que resultan de las claves de unión para evitar redundancia

df_new = df_merged.loc[:, ~df_merged.columns.duplicated()]

In [11]:
df_new.head()

,Genero_Usuario,Edad_Usuario,Bici,Ciclo_Estacion_Retiro,Fecha_Retiro,Hora_Retiro,Ciclo_Estacion_Arribo,Fecha_Arribo,Hora_Arribo,num_cicloe,...,sitio_de_e_Retiro,num_cicloe_Arribo,nombre_estacion_Arribo,calle_prin_Arribo,calle_secu_Arribo,colonia_Arribo,alcaldia_Arribo,latitud_Arribo,longitud_Arribo,sitio_de_e_Arribo
0,M,26.0,5180930,568,31/12/2024,23:57:02,572,01/01/2025,00:00:03,568,...,Arroyo,572,Manuel J. Othón_José T. Cuellar,Manuel J. Othón,José T. Cuellar,Obrera,Cuauhtemoc,19.414595,-99.135886,Arroyo
1,F,54.0,3653953,283,31/12/2024,23:51:40,596,01/01/2025,00:00:41,283,...,Arroyo,596,Cumbres De Maltrata_Uxmal,Cumbres De Maltrata,Uxmal,Narvarte,Benito Juarez,19.395205,-99.155049,Arroyo
2,M,38.0,7511322,34,31/12/2024,23:48:36,64,01/01/2025,00:00:59,34,...,Arroyo,64,Sonora_Ámsterdam,Sonora,Ámsterdam,Hipodromo,Cuauhtemoc,19.412982,-99.166936,Arroyo
3,M,41.0,3804572,258,31/12/2024,23:54:11,23,01/01/2025,00:01:08,258,...,Banqueta,23,Reforma_Praga,Reforma,Praga,Juarez,Cuauhtemoc,19.425280,-99.171099,Banqueta
4,M,35.0,3848405,43,31/12/2024,23:35:28,126,01/01/2025,00:01:17,43,...,Banqueta,126,Jalapa_Puebla,Jalapa,Puebla,Roma Norte,Cuauhtemoc,19.422288,-99.162138,Arroyo

In [12]:
columnas = df_new.columns.tolist()
columnas

['Genero_Usuario',
 'Edad_Usuario',
 'Bici',
 'Ciclo_Estacion_Retiro',
 'Fecha_Retiro',
 'Hora_Retiro',
 'Ciclo_Estacion_Arribo',
 'Fecha_Arribo',
 'Hora_Arribo',
 'num_cicloe',
 'nombre_estacion_Retiro',
 'calle_prin_Retiro',
 'calle_secu_Retiro',
 'colonia_Retiro',
 'alcaldia_Retiro',
 'latitud_Retiro',
 'longitud_Retiro',
 'sitio_de_e_Retiro',
 'num_cicloe_Arribo',
 'nombre_estacion_Arribo',
 'calle_prin_Arribo',
 'calle_secu_Arribo',
 'colonia_Arribo',
 'alcaldia_Arribo',
 'latitud_Arribo',
 'longitud_Arribo',
 'sitio_de_e_Arribo']

In [13]:
df_new.head()

,Genero_Usuario,Edad_Usuario,Bici,Ciclo_Estacion_Retiro,Fecha_Retiro,Hora_Retiro,Ciclo_Estacion_Arribo,Fecha_Arribo,Hora_Arribo,num_cicloe,...,sitio_de_e_Retiro,num_cicloe_Arribo,nombre_estacion_Arribo,calle_prin_Arribo,calle_secu_Arribo,colonia_Arribo,alcaldia_Arribo,latitud_Arribo,longitud_Arribo,sitio_de_e_Arribo
0,M,26.0,5180930,568,31/12/2024,23:57:02,572,01/01/2025,00:00:03,568,...,Arroyo,572,Manuel J. Othón_José T. Cuellar,Manuel J. Othón,José T. Cuellar,Obrera,Cuauhtemoc,19.414595,-99.135886,Arroyo
1,F,54.0,3653953,283,31/12/2024,23:51:40,596,01/01/2025,00:00:41,283,...,Arroyo,596,Cumbres De Maltrata_Uxmal,Cumbres De Maltrata,Uxmal,Narvarte,Benito Juarez,19.395205,-99.155049,Arroyo
2,M,38.0,7511322,34,31/12/2024,23:48:36,64,01/01/2025,00:00:59,34,...,Arroyo,64,Sonora_Ámsterdam,Sonora,Ámsterdam,Hipodromo,Cuauhtemoc,19.412982,-99.166936,Arroyo
3,M,41.0,3804572,258,31/12/2024,23:54:11,23,01/01/2025,00:01:08,258,...,Banqueta,23,Reforma_Praga,Reforma,Praga,Juarez,Cuauhtemoc,19.425280,-99.171099,Banqueta
4,M,35.0,3848405,43,31/12/2024,23:35:28,126,01/01/2025,00:01:17,43,...,Banqueta,126,Jalapa_Puebla,Jalapa,Puebla,Roma Norte,Cuauhtemoc,19.422288,-99.162138,Arroyo

In [14]:
# Definir el nuevo orden de las columnas
nuevo_orden = [
    'Genero_Usuario',
    'Edad_Usuario',
    'Bici',
    'Ciclo_Estacion_Retiro',
    'num_cicloe',
    'nombre_estacion_Retiro',
    'calle_prin_Retiro',
    'calle_secu_Retiro',
    'colonia_Retiro',
    'alcaldia_Retiro',
    'latitud_Retiro',
    'longitud_Retiro',
    'sitio_de_e_Retiro',
    'Fecha_Retiro',
    'Hora_Retiro',
    'Ciclo_Estacion_Arribo',
    'num_cicloe_Arribo',
    'nombre_estacion_Arribo',
    'calle_prin_Arribo',
    'calle_secu_Arribo',
    'colonia_Arribo',
    'alcaldia_Arribo',
    'latitud_Arribo',
    'longitud_Arribo',
    'sitio_de_e_Arribo',
    'Fecha_Arribo',
    'Hora_Arribo'
]

# Reordenar las columnas del DataFrame df_new
df_new = df_new[nuevo_orden]
df_new.head()

,Genero_Usuario,Edad_Usuario,Bici,Ciclo_Estacion_Retiro,num_cicloe,nombre_estacion_Retiro,calle_prin_Retiro,calle_secu_Retiro,colonia_Retiro,alcaldia_Retiro,...,nombre_estacion_Arribo,calle_prin_Arribo,calle_secu_Arribo,colonia_Arribo,alcaldia_Arribo,latitud_Arribo,longitud_Arribo,sitio_de_e_Arribo,Fecha_Arribo,Hora_Arribo
0,M,26.0,5180930,568,568,Doctor Barragán_Doctor Erazo,Doctor Barragán,Doctor Erazo,Doctores,Cuauhtemoc,...,Manuel J. Othón_José T. Cuellar,Manuel J. Othón,José T. Cuellar,Obrera,Cuauhtemoc,19.414595,-99.135886,Arroyo,01/01/2025,00:00:03
1,F,54.0,3653953,283,283,Av. Coyoacán_Rafael Dondé,Av. Coyoacán,Rafael Dondé,Del Valle Norte,Benito Juarez,...,Cumbres De Maltrata_Uxmal,Cumbres De Maltrata,Uxmal,Narvarte,Benito Juarez,19.395205,-99.155049,Arroyo,01/01/2025,00:00:41
2,M,38.0,7511322,34,34,Liverpool_Génova,Liverpool,Génova,Juarez,Cuauhtemoc,...,Sonora_Ámsterdam,Sonora,Ámsterdam,Hipodromo,Cuauhtemoc,19.412982,-99.166936,Arroyo,01/01/2025,00:00:59
3,M,41.0,3804572,258,258,Circuito Interior_Juan Escutia,Circuito Interior,Juan Escutia,Condesa,Cuauhtemoc,...,Reforma_Praga,Reforma,Praga,Juarez,Cuauhtemoc,19.425280,-99.171099,Banqueta,01/01/2025,00:01:08
4,M,35.0,3848405,43,43,Revillagigedo_Juárez,Revillagigedo,Juárez,Centro,Cuauhtemoc,...,Jalapa_Puebla,Jalapa,Puebla,Roma Norte,Cuauhtemoc,19.422288,-99.162138,Arroyo,01/01/2025,00:01:17

In [15]:
# Definir las columnas a eliminar
columnas_a_eliminar = ['num_cicloe', 'num_cicloe_Arribo']

# Eliminar las columnas del DataFrame df_new
df_new = df_new.drop(columns=columnas_a_eliminar)


# Mostrar las primeras filas del DataFrame para confirmar
df_new.head()

,Genero_Usuario,Edad_Usuario,Bici,Ciclo_Estacion_Retiro,nombre_estacion_Retiro,calle_prin_Retiro,calle_secu_Retiro,colonia_Retiro,alcaldia_Retiro,latitud_Retiro,...,nombre_estacion_Arribo,calle_prin_Arribo,calle_secu_Arribo,colonia_Arribo,alcaldia_Arribo,latitud_Arribo,longitud_Arribo,sitio_de_e_Arribo,Fecha_Arribo,Hora_Arribo
0,M,26.0,5180930,568,Doctor Barragán_Doctor Erazo,Doctor Barragán,Doctor Erazo,Doctores,Cuauhtemoc,19.418013,...,Manuel J. Othón_José T. Cuellar,Manuel J. Othón,José T. Cuellar,Obrera,Cuauhtemoc,19.414595,-99.135886,Arroyo,01/01/2025,00:00:03
1,F,54.0,3653953,283,Av. Coyoacán_Rafael Dondé,Av. Coyoacán,Rafael Dondé,Del Valle Norte,Benito Juarez,19.397923,...,Cumbres De Maltrata_Uxmal,Cumbres De Maltrata,Uxmal,Narvarte,Benito Juarez,19.395205,-99.155049,Arroyo,01/01/2025,00:00:41
2,M,38.0,7511322,34,Liverpool_Génova,Liverpool,Génova,Juarez,Cuauhtemoc,19.424584,...,Sonora_Ámsterdam,Sonora,Ámsterdam,Hipodromo,Cuauhtemoc,19.412982,-99.166936,Arroyo,01/01/2025,00:00:59
3,M,41.0,3804572,258,Circuito Interior_Juan Escutia,Circuito Interior,Juan Escutia,Condesa,Cuauhtemoc,19.416530,...,Reforma_Praga,Reforma,Praga,Juarez,Cuauhtemoc,19.425280,-99.171099,Banqueta,01/01/2025,00:01:08
4,M,35.0,3848405,43,Revillagigedo_Juárez,Revillagigedo,Juárez,Centro,Cuauhtemoc,19.435136,...,Jalapa_Puebla,Jalapa,Puebla,Roma Norte,Cuauhtemoc,19.422288,-99.162138,Arroyo,01/01/2025,00:01:17

In [17]:
# Obtener el número de filas y columnas del DataFrame df_new
num_filas, num_columnas = df_new.shape

# Mostrar el número de filas y columnas
print("Número de filas:", num_filas)
print("Número de columnas:", num_columnas)

Número de filas: 22539389
Número de columnas: 25

In [16]:
# Guardar el DataFrame en un nuevo archivo CSV (opcional)
df_new.to_csv('archivo_ordenado.csv', index=True)